import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '架构设计',
      items: [
        'arch/architecture',
        'arch/encode',
        'arch/operation',
        'arch/concepts',
      ],
    },
    {
      type: 'category',
      label: '安装与使用',
      items: [
        'install_and_use/install',
        'install_and_use/use',
      ],
    },
    {
      type: 'category',
      label: 'Walrus部署网站',
      items: [
        'walrus_sites/publish',
        'walrus_sites/ana'
      ],
    },
  ],
  
};

export default sidebars;
